limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=addr:10m;

server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    limit_req zone=mylimit burst=20 nodelay;
    limit_conn addr 10;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(glb|mp3|png|jpg|css|js)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}